service: tg-a1-bot
provider:
  name: aws
  profile: personal
  runtime: nodejs8.10
  region: ap-southeast-1

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-offline
  - serverless-dotenv-plugin

package:
  include:
    - .fonts/**
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  run:
    handler: handler.run
    memorySize: 1536MB
    timeout: 900
    events:
      - schedule: cron(0 0 * * ? *)
