service: tg-a1-bot
provider:
  name: aws
  profile: personal
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 1536
  timeout: 900

functions:
  scheduled:
    handler: scheduled.scheduled
    events:
      - schedule: cron(0 0 * * ? *)
  webhook:
    handler: webhook.webhook
    events:
      - http:
          path: webhook
          method: post
          cors: true

package:
  include:
    - .fonts/**
  exclude:
    - node_modules/puppeteer/.local-chromium/**

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-offline
  - serverless-dotenv-plugin
